// TaxiHUB 2.0 â€” Iconografía curada (lucide). Un solo estilo en todo el producto.
// Importar desde aquí, no directamente de lucide-react, para mantener el catálogo.
export {
  // Operación
  PhoneCall,
  MessageCircle,
  Radio,
  MapPin,
  Navigation,
  Flag,
  RouteIcon,
  LocateFixed,
  Crosshair,
  // Flota y conductores
  Car,
  CarFront,
  Truck,
  User,
  Users,
  IdCard,
  Contact,
  // Estados y alertas
  CircleDot,
  AlertTriangle,
  Ban,
  AlertCircle,
  CheckCircle2,
  XCircle,
  Check,
  ClipboardCheck,
  Clock,
  Clock3,
  Zap,
  // Mantenimiento / combustible / documentos
  Wrench,
  Fuel,
  Gauge,
  FileText,
  FileCheck,
  CalendarClock,
  // Socios / administración
  Briefcase,
  Building2,
  Wallet,
  Receipt,
  BarChart3,
  TrendingUp,
  PieChart,
  // Navegación / sistema
  LayoutDashboard,
  LayoutPanelLeft,
  Filter,
  Menu,
  Repeat,
  List,
  Settings,
  LogOut,
  Search,
  Plus,
  Minus,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  CornerDownLeft,
  ArrowLeft,
  RefreshCw,
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Signal,
  Satellite,
  // Acciones de servicio
  Phone,
  ClipboardList,
  Send,
  ExternalLink,
  History,
  PackageOpen,
} from "lucide-react";
